// Copyright 2026 Li Qiankun
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package executor owns the process-bearing part of a bed. A bed is durable
// data identity; its Executor is an ephemeral, replaceable process realm.
package executor

import (
	"context"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"os/exec"
)

// State is an Executor's lifecycle state.
type State string

const (
	StateStarting State = "starting"
	StateReady    State = "ready"
	StateDraining State = "draining"
	StateStopped  State = "stopped"
	StateLost     State = "lost"
)

// ProcessOutcome is the kernel-level terminal fact for one started process.
// Intent such as timeout or teardown belongs to the higher-level Execution.
type ProcessOutcome struct {
	Kind       ProcessOutcomeKind
	ExitCode   int
	Signal     int
	CoreDumped bool
	Error      string
	// Detail is retained for server-side diagnostics and never projected to
	// clients. Public APIs expose a stable executor-lost error, not transport
	// artifacts such as EOF or a Unix-socket reset.
	Detail string
}

type ProcessOutcomeKind string

const (
	ProcessExited   ProcessOutcomeKind = "exited"
	ProcessSignaled ProcessOutcomeKind = "signaled"
	ProcessLost     ProcessOutcomeKind = "lost"
)

func Exited(code int) ProcessOutcome {
	return ProcessOutcome{Kind: ProcessExited, ExitCode: code}
}

func Signaled(signal int, coreDumped bool) ProcessOutcome {
	return ProcessOutcome{Kind: ProcessSignaled, Signal: signal, CoreDumped: coreDumped}
}

func Lost(executorID string, err error) ProcessOutcome {
	message := fmt.Sprintf("executor %s lost", executorID)
	detail := ""
	if err != nil {
		detail = err.Error()
	}
	return ProcessOutcome{Kind: ProcessLost, Error: message, Detail: detail}
}

func processSpecHash(cmd *exec.Cmd) string {
	payload, _ := json.Marshal(struct {
		Path string   `json:"path"`
		Args []string `json:"args"`
		Dir  string   `json:"dir"`
		Env  []string `json:"env"`
	}{Path: cmd.Path, Args: cmd.Args, Dir: cmd.Dir, Env: cmd.Env})
	return fmt.Sprintf("%x", sha256.Sum256(payload))
}

// Process is one OS process started inside an Executor. Wait is safe to call
// more than once and always returns the same terminal fact.
type Process interface {
	ID() string
	PID() int
	Kill()
	Wait(context.Context) (ProcessOutcome, error)
}

// Exit describes why an Executor stopped.
type Exit struct {
	State State
	Err   error
}

// Executor is one Bed's current process realm. Process IDs are generated by
// the caller so Start can be retried idempotently across transport failures.
type Executor interface {
	ID() string
	BedID() string
	Backend() string
	State() State
	Start(context.Context, string, *exec.Cmd) (Process, error)
	Shutdown(context.Context) error
	Done() <-chan struct{}
	Exit() Exit
}

// Factory creates a fresh Executor identity for a Bed.
type Factory interface {
	Backend() string
	Create(context.Context, string) (Executor, error)
	Close() error
}
